version: '3.8'

services:
  postgres-catalog:
    image: postgres:15-alpine
    container_name: iceberg-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iceberg_catalog
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: iceberg-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  trino-server:
    image: trinodb/trino:latest
    container_name: iceberg-trino
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./trino_catalog
        target: /etc/trino/catalog
    depends_on:
      - postgres-catalog
      - minio

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: iceberg-superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=kiva_lakehouse_secret_key_2026