connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres-catalog:5432/iceberg_catalog
iceberg.jdbc-catalog.connection-user=admin
iceberg.jdbc-catalog.connection-password=password
iceberg.jdbc-catalog.catalog-name=trino_cat
iceberg.jdbc-catalog.default-warehouse-dir=file:///D:/abd/tubes/Kelompok-2_Tanpa-Kemiskinan/warehouse